"""initial commit

Revision ID: 3ce357d99fac
Revises: 
Create Date: 2024-03-03 20:04:42.545640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce357d99fac'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_car', sa.String(length=20), nullable=False),
    sa.Column('driver', sa.String(length=100), nullable=False),
    sa.Column('passenger', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('cmc_code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('number_car', name=op.f('uq_orders_number_car'))
    )
    op.create_table('taxi_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('driver', sa.String(length=100), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taxi_service')),
    sa.UniqueConstraint('number', name=op.f('uq_taxi_service_number'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxi_service')
    op.drop_table('orders')
    # ### end Alembic commands ###
